#############################################################################
# Generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#  Jun 08, 2020 09:31:25 AM +07  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m50" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #ffffff 
    wm focusmodel $top passive
    wm geometry $top 1366x705+1642+70
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3290 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can49 \
        -background #ffffff -height 290 -highlightbackground #ffffff \
        -highlightcolor #ffffff -insertbackground #ffffff -relief ridge \
        -selectbackground #ffffff -selectforeground #ffffff -takefocus 0 \
        -width 428 
    vTcl:DefineAlias "$top.can49" "CanvasCurrent" vTcl:WidgetProc "Window" 1
    text $top.tex58 \
        -background white -font {-family {Segoe UI} -size 12} \
        -foreground black -height 268 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -takefocus 0 -width 308 -wrap word 
    $top.tex58 configure -font "-family {Segoe UI} -size 12"
    $top.tex58 insert end text
    vTcl:DefineAlias "$top.tex58" "TextConsole" vTcl:WidgetProc "Window" 1
    button $top.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Check Screen Position} 
    vTcl:DefineAlias "$top.but60" "ButtonScreenCorrection" vTcl:WidgetProc "Window" 1
    canvas $top.can44 \
        -background #000000 -closeenough 1.0 -height 290 \
        -highlightbackground #000000 -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #000000 \
        -selectforeground black -takefocus 0 -width 431 
    vTcl:DefineAlias "$top.can44" "CanvasReference" vTcl:WidgetProc "Window" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Current Screen} 
    vTcl:DefineAlias "$top.lab46" "LabelCurrentScreen" vTcl:WidgetProc "Window" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 18 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Reference Screen} 
    vTcl:DefineAlias "$top.lab47" "LabelReferenceScreen" vTcl:WidgetProc "Window" 1
    button $top.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Check Reference Image} 
    vTcl:DefineAlias "$top.but44" "ButtonCheckReference" vTcl:WidgetProc "Window" 1
    text $top.tex44 \
        -background white -font {-family {Segoe UI} -size 10} \
        -foreground black -height 291 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -takefocus 0 -width 305 -wrap word 
    $top.tex44 configure -font "-family {Segoe UI} -size 10"
    $top.tex44 insert end text
    vTcl:DefineAlias "$top.tex44" "TextReference" vTcl:WidgetProc "Window" 1
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Created by Thien Nguyen} 
    vTcl:DefineAlias "$top.lab45" "LabelAuthor" vTcl:WidgetProc "Window" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Control History} 
    vTcl:DefineAlias "$top.lab49" "LabelControlHistory" vTcl:WidgetProc "Window" 1
    set site_3_0 $top.m50
    menu $site_3_0 \
        -activebackground SystemHighlight \
        -activeforeground SystemHighlightText \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab44 \
        -font TkDefaultFont -foreground black -text {Auto Control By Script} \
        -background $vTcl(actual_gui_bg) -height 285 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 430 
    vTcl:DefineAlias "$top.lab44" "FrameAutoControl" vTcl:WidgetProc "Window" 1
    set site_3_0 $top.lab44
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Stop Test} 
    vTcl:DefineAlias "$site_3_0.but50" "ButtonStop" vTcl:WidgetProc "Window" 1
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Pause Test} 
    vTcl:DefineAlias "$site_3_0.but51" "ButtonPause" vTcl:WidgetProc "Window" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Start Test} 
    vTcl:DefineAlias "$site_3_0.but52" "ButtonStart" vTcl:WidgetProc "Window" 1
    entry $site_3_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 364 
    vTcl:DefineAlias "$site_3_0.ent53" "InputScript" vTcl:WidgetProc "Window" 1
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Load Script} 
    vTcl:DefineAlias "$site_3_0.but54" "ButtonLoad" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Input the script (*.xlsx) path below or press the "Load Script"} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label1" vTcl:WidgetProc "Window" 1
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.7 -y 0 -rely 0.717 -width 100 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.375 -y 0 -rely 0.717 -width 100 \
        -relwidth 0 -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.05 -y 0 -rely 0.717 -width 100 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent53 \
        -in $site_3_0 -x 0 -relx 0.05 -y 0 -rely 0.453 -width 364 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.375 -y 0 -rely 0.113 -width 100 \
        -relwidth 0 -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.088 -y 0 -rely 0.358 -width 0 \
        -relwidth 0.835 -height 0 -relheight 0.079 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab57 \
        -font TkDefaultFont -foreground black -text {Manual Control} \
        -background $vTcl(actual_gui_bg) -height 285 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 431 
    vTcl:DefineAlias "$top.lab57" "Labelframe1" vTcl:WidgetProc "Window" 1
    set site_3_0 $top.lab57
    button $site_3_0.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text System 
    vTcl:DefineAlias "$site_3_0.but58" "ButtonSystem" vTcl:WidgetProc "Window" 1
    button $site_3_0.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text DTC 
    vTcl:DefineAlias "$site_3_0.but59" "ButtonDTC" vTcl:WidgetProc "Window" 1
    button $site_3_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Erase 
    vTcl:DefineAlias "$site_3_0.but60" "ButtonErase" vTcl:WidgetProc "Window" 1
    button $site_3_0.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Menu 
    vTcl:DefineAlias "$site_3_0.but61" "ButtonMenu" vTcl:WidgetProc "Window" 1
    button $site_3_0.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Relink 
    vTcl:DefineAlias "$site_3_0.but62" "ButtonLink" vTcl:WidgetProc "Window" 1
    button $site_3_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text LD 
    vTcl:DefineAlias "$site_3_0.but63" "ButtonLD" vTcl:WidgetProc "Window" 1
    button $site_3_0.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Enter 
    vTcl:DefineAlias "$site_3_0.but64" "ButtonEnter" vTcl:WidgetProc "Window" 1
    button $site_3_0.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Left Softkey} 
    vTcl:DefineAlias "$site_3_0.but65" "ButtonSoftkeyLeft" vTcl:WidgetProc "Window" 1
    button $site_3_0.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Right Softkey} 
    vTcl:DefineAlias "$site_3_0.but66" "ButtonSoftkeyRight" vTcl:WidgetProc "Window" 1
    button $site_3_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Capture 
    vTcl:DefineAlias "$site_3_0.but70" "ButtonCapture" vTcl:WidgetProc "Window" 1
    button $site_3_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Compare 
    vTcl:DefineAlias "$site_3_0.but71" "ButtonCompare" vTcl:WidgetProc "Window" 1
    checkbutton $site_3_0.che73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -height 35 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Power 1} -variable che73 
    vTcl:DefineAlias "$site_3_0.che73" "CheckPower1" vTcl:WidgetProc "Window" 1
    bind $site_3_0.che73 <<SetBalloon>> {
        set ::vTcl::balloon::%W {che73}
    }
    checkbutton $site_3_0.che74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Power 2} -variable che74 
    vTcl:DefineAlias "$site_3_0.che74" "CheckPower2" vTcl:WidgetProc "Window" 1
    checkbutton $site_3_0.che75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Power 3} -variable che74 
    vTcl:DefineAlias "$site_3_0.che75" "CheckPower3" vTcl:WidgetProc "Window" 1
    checkbutton $site_3_0.che76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {USB 1} -variable UBS_1 
    vTcl:DefineAlias "$site_3_0.che76" "CheckUSB1" vTcl:WidgetProc "Window" 1
    checkbutton $site_3_0.che77 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {USB 2} -variable che74 
    vTcl:DefineAlias "$site_3_0.che77" "CheckUSB2" vTcl:WidgetProc "Window" 1
    checkbutton $site_3_0.che78 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Power 4} -variable che74 
    vTcl:DefineAlias "$site_3_0.che78" "CheckPower4" vTcl:WidgetProc "Window" 1
    button $site_3_0.but44 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Up 
    vTcl:DefineAlias "$site_3_0.but44" "ButtonUp" vTcl:WidgetProc "Window" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text Down 
    vTcl:DefineAlias "$site_3_0.but45" "ButtonDown" vTcl:WidgetProc "Window" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 134 
    vTcl:DefineAlias "$site_3_0.ent46" "TextReport" vTcl:WidgetProc "Window" 1
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text ... 
    vTcl:DefineAlias "$site_3_0.but47" "ButtonSelectReport" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {save report file to ...} 
    vTcl:DefineAlias "$site_3_0.lab48" "LabelReport" vTcl:WidgetProc "Window" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Enable Keyboard Control} 
    vTcl:DefineAlias "$site_3_0.but48" "ButtonEnableKeyboard" vTcl:WidgetProc "Window" 1
    place $site_3_0.but58 \
        -in $site_3_0 -x 0 -relx 0.046 -y 0 -rely 0.632 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 0 -relx 0.046 -y 0 -rely 0.842 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 0 -relx 0.046 -y 0 -rely 0.421 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 0 -relx 0.418 -y 0 -rely 0.632 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 0 -relx 0.418 -y 0 -rely 0.421 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 0 -relx 0.418 -y 0 -rely 0.842 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 0 -relx 0.232 -y 0 -rely 0.611 -width 50 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.281 -width 90 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but66 \
        -in $site_3_0 -x 0 -relx 0.348 -y 0 -rely 0.281 -width 100 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 0 -relx 0.023 -y 0 -rely 0.081 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 0 -relx 0.348 -y 0 -rely 0.077 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che73 \
        -in $site_3_0 -x 0 -relx 0.58 -y 0 -rely 0.526 -width 0 \
        -relwidth 0.202 -height 0 -relheight 0.133 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che74 \
        -in $site_3_0 -x 0 -relx 0.789 -y 0 -rely 0.54 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che75 \
        -in $site_3_0 -x 0 -relx 0.603 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che76 \
        -in $site_3_0 -x 0 -relx 0.589 -y 0 -rely 0.842 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che77 \
        -in $site_3_0 -x 0 -relx 0.777 -y 0 -rely 0.842 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che78 \
        -in $site_3_0 -x 0 -relx 0.789 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.153 -height 0 -relheight 0.095 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 0 -relx 0.232 -y 0 -rely 0.421 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 0 -relx 0.232 -y 0 -rely 0.842 -width 50 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.603 -y 0 -rely 0.116 -width 134 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.928 -y 0 -rely 0.105 -width 27 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.626 -y 0 -rely 0.035 -width 0 \
        -relwidth 0.311 -height 0 -relheight 0.074 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.603 -y 0 -rely 0.281 -width 167 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab57
    ttk::combobox $top.tCo83 \
        -values {{(Select driver port)}} -font {-family {Segoe UI} -size 11} \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo83" "ListDriver" vTcl:WidgetProc "Window" 1
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Connect Camera} 
    vTcl:DefineAlias "$top.but45" "ButtonCamaraConnect" vTcl:WidgetProc "Window" 1
    spinbox $top.spi47 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font {-family {Segoe UI} -size 11} \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -justify center -selectbackground #c4c4c4 -selectforeground black \
        -textvariable spinbox -to 100.0 -values {1 2 3 4 5 0 {}} 
    vTcl:DefineAlias "$top.spi47" "Spinbox1" vTcl:WidgetProc "Window" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -takefocus 0 -text {Connect Driver Board} 
    vTcl:DefineAlias "$top.but48" "ButtonDriver" vTcl:WidgetProc "Window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can49 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.071 -width 0 -relwidth 0.313 \
        -height 0 -relheight 0.411 -anchor nw -bordermode ignore 
    place $top.tex58 \
        -in $top -x 0 -relx 0.747 -y 0 -rely 0.553 -width 0 -relwidth 0.225 \
        -height 0 -relheight 0.38 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 0 -relx 0.256 -y 0 -rely 0.482 -width 127 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.can44 \
        -in $top -x 0 -relx 0.395 -y 0 -rely 0.057 -width 0 -relwidth 0.316 \
        -height 0 -relheight 0.411 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.014 -width 0 -relwidth 0.151 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.432 -y 0 -rely 0.014 -width 0 -relwidth 0.245 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 0 -relx 0.791 -y 0 -rely 0.014 -width 177 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex44 \
        -in $top -x 0 -relx 0.747 -y 0 -rely 0.057 -width 0 -relwidth 0.223 \
        -height 0 -relheight 0.413 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.366 -y 0 -rely 0.965 -width 0 -relwidth 0.171 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.805 -y 0 -rely 0.511 -width 0 -relwidth 0.1 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 0 -relx 0.395 -y 0 -rely 0.539 -width 0 -relwidth 0.315 \
        -height 0 -relheight 0.404 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.539 -width 0 -relwidth 0.316 \
        -height 0 -relheight 0.404 -anchor nw -bordermode ignore 
    place $top.tCo83 \
        -in $top -x 0 -relx 0.556 -y 0 -rely 0.482 -width 0 -relwidth 0.12 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 0 -relx 0.037 -y 0 -rely 0.482 -width 157 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.spi47 \
        -in $top -x 0 -relx 0.161 -y 0 -rely 0.482 -width 0 -relwidth 0.041 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.432 -y 0 -rely 0.482 -width 157 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

